# Generated by Django 6.0.3 on 2026-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('superadmin', 'Супер администратор'), ('content_manager', 'Контент менеджер'), ('operator', 'Оператор')], default='operator', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('оффлайн', 'Оффлайн'), ('онлайн', 'Онлайн')], max_length=10)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=15)),
                ('admin_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(blank=True, choices=[('оффлайн', 'Оффлайн'), ('онлайн', 'Онлайн')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='not_started', max_length=15)),
                ('modules_progress', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_program', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('price_offline', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_online', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offline_available', models.BooleanField(blank=True, null=True)),
                ('online_available', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('archive', 'В архиве')], default='active', max_length=10)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField()),
                ('type', models.CharField(choices=[('news', 'Новость'), ('promo', 'Акция'), ('event', 'Событие')], default='news', max_length=10)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('course_available', 'Курс доступен'), ('favorite_update', 'Обновление избранного'), ('system', 'Системное'), ('promo', 'Акция')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Фотография (файл)')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL фотографии (ссылка)')),
                ('author_type', models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент/Выпускник')], max_length=20, verbose_name='Тип автора')),
                ('author_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя автора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'db_table': 'portfolio',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('biography', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('theme_preference', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'db_table': 'work_type',
                'managed': False,
            },
        ),
    ]
