# Generated by Django 6.0.3 on 2026-05-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_alt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Доп. телефон')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admins',
            options={'managed': False, 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'managed': False, 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'managed': False, 'verbose_name': 'Прогресс обучения', 'verbose_name_plural': 'Прогресс студентов'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False, 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'managed': False, 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные курсы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'managed': False, 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'managed': False, 'verbose_name': 'преподаватель', 'verbose_name_plural': 'преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
