# Generated by Django 6.0.3 on 2026-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_profile_alter_admins_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID модуля')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'db_table': 'modules',
                'ordering': ['order', 'module_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('module_progress_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID прогресса модуля')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='not_started', max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Прогресс модуля',
                'verbose_name_plural': 'Прогресс модулей',
                'db_table': 'module_progress',
                'managed': False,
            },
        ),
    ]
