# Generated by Django 6.0.5 on 2026-05-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'managed': True, 'verbose_name': 'Прогресс обучения', 'verbose_name_plural': 'Прогресс студентов'},
        ),
    ]
